### ISSUE TITLE
Show more infos about tier sets

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#15]
Show which tier pieces a character has equiped.
e.g. show number of tier pieces in a new column and then show in the tooltipp which exact tier piece is equiped.

Bonus: show a summary how many helms, shoulders, chests, ... are missing for the whole group.
Super-Bonus: Only count those characters which don't have minimum 4 set pieces.

**Comment by derwhite** [comment]
T-Sets are great and give a big buff, but i don't want to add a new column to the Table. I don't want to make the table to width. Now we have 8 instances and Blizzard decided in the last 2 expansions that in S3 / S4 that we have 10 instances for mythic+. So the width is almost on limit with 10 dungeons and the column width. :<

We can put a little more detailed information on T-Sets in the Tooltip as an alternativ, but adding columns needs a lot of testing that we dont have to scroll or its looks bad on mobile devices.

**Comment by derwhite** [comment]
Actually i force the table to be 100% on screen and the only column without force a fixed size is "Player".
Score is 8%
every dungeon is 8%
actually we have 8% * 8% + 8% = 72% width fixed. (Player field is really big now.)
but if we add 2 instances, its gets really small.... i did a lot of testings in the beginning and if i remember correct i got a line break if i did Instances down to 7%, but i'm not 100% sure. (this is something we need to watch out for.)

If you have a good example of it or ideas how we can manage it better (i don't now a lot of HTML tables) than let me know.

**Comment by Kaeseknacker** [comment]
Good point that we don't neglect table size.

But I doubt that they will do another season with more than 8 dungeons. SL-S4 was also a 8-Dungeon-Season.
Their new strategy is: 4 new Dungeons + 4 old Dungeons

**Comment by Kaeseknacker** [comment]
Issue is solved. I think the Bonus-Tasks are currently not required.
