### ISSUE TITLE
Table headings are visible when scrolling.

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#16]
Bug of Feature? It looks weird.

![grafik](https://user-images.githubusercontent.com/20515981/213709859-34889acd-83bd-4603-a9b1-ac8048914d5e.png)

**Comment by derwhite** [comment]
This is a Feature... if youu have a small screen, that you're able to see what instance it is. I don't like how it looks, but that was the best i could get ;D

**Comment by Kaeseknacker** [comment]
Looks realy great now!
