### ISSUE TITLE
Show dungeon timer breakpoints

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#17]
Blizzard API gives us also the dungeon timer breakpoints. We could show them in the dungeon tooltip.

**Comment by derwhite** [comment]
Done... I thought it is easier to do it without API, but shortly after i commited it, is saw, thats no problem at all to do it with the API... so i did another commit ;D

**Comment by Kaeseknacker** [comment]
Looks great! Yeah we could calc these timers by ourself. Didn't know before that +2 is 80% and +3 is 60% of the timer. But when we already pulled that info we could also use it. Maybe Blizzard changes this for some strange reason.

Tipp: If you add the Issues Number (e.g. #17) at the beginning of your commit message github will automaticaly link the commit(s) to the related issue. I just found that out by accident, but it's a cool feature.
