### ISSUE TITLE
Show Instance Icons

### ISSUE THREAD

**Issue by derwhite** [derwhite/whitez_mplus#24]
I would like to have small Icons on the Dungeons as well... (Maybe like the Icons ingame)

![grafik](https://user-images.githubusercontent.com/18561153/217834630-4f46dc9a-67ce-46d0-bf0f-4d20bb910a06.png)

but i dont know, where to get them 🤣

**Comment by derwhite** [comment]
Maybe these are the loading screens from the Dungeon. 🤔

**Comment by derwhite** [comment]
like so:
![grafik](https://user-images.githubusercontent.com/18561153/217853714-8fa0cec6-1766-4dc2-b18b-002ad3efed6a.png)

**Comment by Kaeseknacker** [comment]
where do you pull these images?

**Comment by derwhite** [comment]
i have no idea ^^... downloaded an test image and tryed to implement it. I don't know where to get these automated, so maybe i upload some screenshots to my web-server ^^

**Comment by Kaeseknacker** [comment]
I have no problems with adding some images to the project. The result looks really good.

**Comment by Kaeseknacker** [comment]
I would recommend a resources folder with the images:
```
resources/favicon.png
resources/instances/DF/RLP.png
resources/instances/DF/AA.png
...
```
Inside the code we just use a simple dictionary:
```python
{
    "AA": "resources/instances/DF/AA.png"
    "RLP": "resources/instances/DF/RLP.png"
    # ...
}
```
Also we have to deploy these resources to the webserver/output folder.

**Comment by derwhite** [comment]
Maybe we don't even need a dict for the Images ... 🤔 but now i used one. I had to add some CSS... hopefully you're fine with my solution ^^ The best on this actual solution is, if it doesn't find an image... the background is still black, no problem at all.

**Comment by derwhite** [comment]
and we can add them to the Weekly table, just by link the class to <td> field...
but for me, it looks a little wierd, so i didn't put it in now ... maybe you can try this personally an give me some feedback ^^
(maybe, it looks better with a little boarder or something on the weekly page... idk)

**Comment by Kaeseknacker** [comment]
Looks great. I would do without it in the weekly table. I think it gets too confusing otherwise
