### ISSUE TITLE
Show Affixes for next week

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#26]
Use a List which contains the current affix rotation to look up the affixes for the next week.

If some affixes are missing (e.g. if a new season is released) just don't show this feature until the rotation look up table is fixed.

**Comment by derwhite** [comment]
You also need to check, if your predicted affixes, match the current ones. ❤️

**Comment by Kaeseknacker** [comment]
Took a little bit longer than I thought. I had to pull the additional affix infos (like icon, text) from bnet api.
Currently only the affixes for the following week is shown. But we can simply extend this functionality to show affixes for more weeks in the future.
If the bnet API isn't available, only the current affixes are shown.

The HTML formatting could also be tweaked a bit, but I currently just didn't have the time/joy to do so. :)

**Comment by Kaeseknacker** [comment]
For formatting, we should use an (invisible) table so that the affixes are nicely centered.

**Comment by derwhite** [comment]
> but I currently just didn't have the time/joy to do so. :)

I feel bad again when I read that it's not fun for you. :( If you don't have time, that's no problem. But if you don't have fun, that's an even bigger problem. This is and should remain a fun project, so don't put too much energy into it if you don't enjoy it. This should not turn into work, so I'm always trying to make sure I don't have to constantly update something. I don't want any extra work on top of my real job either.
