### ISSUE TITLE
Show detailed score info

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#28]
As a multi spec player I'm interested in my different m+ scores (Tank/DD/Healer).

In the first iteration we could show this info in the score tooltip.

Perhaps the leaderboard position is also of interest.

**Comment by derwhite** [comment]
![grafik](https://user-images.githubusercontent.com/18561153/218579719-b242d21b-dc99-4eb8-83b9-1c2d828833ca.png)

How do you like this ? its just a quick build only to see how it looks... 

I think if everyone has 2 specs with high scores it doesn't look good ^^ but if we mad the 2nd spec only appear if its reaches some points of the Main score or so... and then we add a little tank, heal or dps icon in front of it. Maybe not to bad. Full score list in Tooltip is fine. btw, the colors in my screenshot are incorrect ^^
and yes, it can only show the two highest score directly on table. (if we wanna do this)

If we don't make it with 2 Lines, i like the idea of having a spec role in front of the score 🤔

**Comment by Kaeseknacker** [comment]
I would not display multiple scores at once. That gets way too confusing.
Above all, you would always have to display 3 scores directly: the total score, roll 1 score, roll 2 score.

But I like the idea with the icons. I think we can add these icons to the tooltip.
