### ISSUE TITLE
optional arguments

### ISSUE THREAD

**Issue by derwhite** [derwhite/whitez_mplus#3]
Can we get an --min_ilvl Argument?

Or some fancy stuff like smart min_ilvl based on Season?

**Comment by Kaeseknacker** [comment]
min_ilvl as an cli-argument isn't a good idea. It is nothing that changes often.
I would suggest a config file with key-value pairs like this: https://docs.python.org/3/library/configparser.html
In this file we can also store proxy settings or the WREWARD list.
