### ISSUE TITLE
Use a own character class instead of the pure response objects

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#5]
Currently the whole code works with the pure response objects. Every time something like p.json()['key1']['key2'] is done...

Make the code more object orientated and introduce a `class Character`.
This class takes the pull response from raider.io and creates a valid Character object which holds every necessary information about this player character.

e.g.:
```Python
class Character:
    def __init__(self, rio_response):
        self._iLvl = rio_response.json()['ilvl']
        self._rio_score = rio_response.json()['score']
        ...
```

**Comment by derwhite** [comment]
You're right... Thats a lot better than the actual code. But my time to this project is very little. Feel free if u want to do that much time into it. If u need any help at any point, just tell me :)

**Comment by Kaeseknacker** [comment]
I implemented a `class Player` which holds all relevant player/character information.
There is still some work to do because at some points there are still some `player._data[...]` calls.
In the future direct access to the self._data field should be prevented.
