### ISSUE TITLE
Different colors for the same key level

### ISSUE THREAD

**Issue by Kaeseknacker** [derwhite/whitez_mplus#7]
![grafik](https://user-images.githubusercontent.com/20515981/213638924-742eccac-4c11-4cb2-a1f5-e17fb9449dc2.png)
vs
![grafik](https://user-images.githubusercontent.com/20515981/213639013-6c3abac6-9997-440c-ad8d-d425b0181c75.png)

Why is the same key level shown in different colors?

**Comment by derwhite** [comment]
This is totally wanted by me and i wanna stick to it.

Short: The color of the Keystone lvl has to do with its base score. To quickly compare 2 runs U see it... If 15 is green and the other 14 is blue, the 14 gives more Points... U can also score a 20 keystone with 100% overtime, it gets white with 0 Points

**Comment by derwhite** [comment]
My old system was exactly like U want, every key level has 1 color ... I like this new colorfull table more, because its also adjusts with the best run on table, down to 0... So the best run is Always legendary and then goes down to epic, blue,Green and white

**Comment by Kaeseknacker** [comment]
Mhh ok, I get it. So the coloring is table based and not key level based.

The problem would also be solved if we put mains and alts in one table with additional filter buttons.
